Skip emitting public_names when executable mode is js
If an executable mode contains, public_name(s), Dune thinks, it's
either,

- exe
- native
- byte

```
1 | (executables (names TestProjectApp)
2 |     (modules (:standard \ TestProjectSrcBinPesyModules))
3 |     (public_names TestProjectApp) (libraries TestProjectSrcBinPesyModules)
4 |     (modes js) (flags -open TestProjectSrcBinPesyModules)
5 |     (preprocess (pps js_of_ocaml-ppx)))
Error: No installable mode found for these executables.
When public_name is set, one of the following modes is required:
- exe
- native
- byte
```

This commits skips emitting public_names if the `modes` field is set
to JS